export const MEDICAL_TAGS = [
  "abdominoplastia",
  "abordagem humanizada",
  "acne",
  "acompanhamento",
  "acompanhamento gestacional",
  "alergia alimentar",
  "alopecia",
  "amamentação",
  "amígdalas",
  "anemia",
  "ansiedade",
  "apendicite",
  "apneia",
  "apneia infantil",
  "artrite",
  "artrite juvenil",
  "asma",
  "astigmatismo",
  "atraso de fala",
  "aumento de amígdalas",
  "autoconhecimento",
  "avc",
  "azia",
  "bactérias",
  "baseada em evidências",
  "biópsia",
  "botox",
  "bronquite",
  "catarata",
  "cefaleia",
  "checkup",
  "cirrose",
  "coagulação",
  "colesterol",
  "congênitas",
  "constipação",
  "corrimento",
  "crescimento",
  "câncer de mama",
  "cólica renal",
  "deficiências",
  "depressão",
  "dermatite",
  "dermatite atópica",
  "desequilíbrio",
  "desvio de septo",
  "diabetes",
  "diarreia",
  "disfagia",
  "disfonia",
  "doença pulmonar",
  "dor articular",
  "dor crônica",
  "dor lombar",
  "dor mamária",
  "dor pélvica",
  "dor torácica",
  "dores inespecíficas",
  "ecg",
  "ecocardiograma",
  "endoscopia",
  "entorse",
  "enxaqueca",
  "epilepsia",
  "escleroterapia",
  "escoliose",
  "esteatose",
  "estética",
  "estética nasal",
  "exame de vista",
  "exercícios",
  "falta de ar",
  "febre",
  "fibromialgia",
  "fragilidade",
  "gastrite",
  "glaucoma",
  "gravidez",
  "hemangioma",
  "hemodiálise",
  "hemoglobina",
  "hemorroidas",
  "hepatite",
  "hepatites",
  "hipertensão",
  "hipotireoidismo",
  "hiv",
  "hérnia",
  "hérnia de disco",
  "icterícia",
  "incontinência",
  "infecção urinária",
  "infecção urinária infantil",
  "infertilidade",
  "insuficiência renal",
  "insônia",
  "joelho",
  "labirintite",
  "laser",
  "lombalgia",
  "lúpus",
  "lúpus infantil",
  "malformações",
  "manchas infantis",
  "melasma",
  "memória",
  "menopausa",
  "miopia",
  "má circulação",
  "mínima invasão",
  "nódulos",
  "obesidade",
  "ombro",
  "oncogenética",
  "otite",
  "palpitação",
  "parto",
  "peeling",
  "perda de peso",
  "planejamento reprodutivo",
  "plano alimentar",
  "plaquetas",
  "polifarmácia",
  "postura",
  "preenchimento",
  "prematuridade",
  "pressão alta",
  "preventivo",
  "prevenção",
  "prolapso",
  "proteinúria",
  "pré-natal",
  "próstata",
  "psoríase",
  "puberdade",
  "pânico",
  "pólipos",
  "qualidade de vida",
  "quedas",
  "quimioterapia",
  "radiculopatia",
  "rastreamento",
  "reabilitação",
  "reconstrutora",
  "reeducação alimentar",
  "refluxo",
  "relacionamentos",
  "rem comportamental",
  "respiração nasal",
  "rinite",
  "rinite alérgica",
  "rinoplastia",
  "sangramento",
  "sangramento retal",
  "sinusite",
  "sonambulismo",
  "sop",
  "sopros",
  "síndrome metabólica",
  "tdah adulto",
  "tendinite",
  "tireoide infantil",
  "tontura",
  "tpm",
  "triagem",
  "trombose",
  "ultrassom",
  "urticária",
  "vacinas",
  "varizes",
  "vertigem",
  "vestibular",
  "vesícula",
  "virose",
  "viroses",
  "vitaminas",
  "vppb"
] as const;
